/* This file generated by mknames.awk do not edit! */
#include <stdio.h>
#include <string.h>
#include "sizes.h"
#include "mapi_names.h"

char* get_mapi_name_str(uint16 d)
{
    char* str = NULL;
    switch(d) {
    case MAPI_ACKNOWLEDGEMENT_MODE:
        str=strdup("MAPI_ACKNOWLEDGEMENT_MODE");
        break;
    case MAPI_ALTERNATE_RECIPIENT_ALLOWED:
        str=strdup("MAPI_ALTERNATE_RECIPIENT_ALLOWED");
        break;
    case MAPI_AUTHORIZING_USERS:
        str=strdup("MAPI_AUTHORIZING_USERS");
        break;
    case MAPI_AUTO_FORWARD_COMMENT:
        str=strdup("MAPI_AUTO_FORWARD_COMMENT");
        break;
    case MAPI_AUTO_FORWARDED:
        str=strdup("MAPI_AUTO_FORWARDED");
        break;
    case MAPI_CONTENT_CONFIDENTIALITY_ALGORITHM_ID:
        str=strdup("MAPI_CONTENT_CONFIDENTIALITY_ALGORITHM_ID");
        break;
    case MAPI_CONTENT_CORRELATOR:
        str=strdup("MAPI_CONTENT_CORRELATOR");
        break;
    case MAPI_CONTENT_IDENTIFIER:
        str=strdup("MAPI_CONTENT_IDENTIFIER");
        break;
    case MAPI_CONTENT_LENGTH:
        str=strdup("MAPI_CONTENT_LENGTH");
        break;
    case MAPI_CONTENT_RETURN_REQUESTED:
        str=strdup("MAPI_CONTENT_RETURN_REQUESTED");
        break;
    case MAPI_CONVERSATION_KEY:
        str=strdup("MAPI_CONVERSATION_KEY");
        break;
    case MAPI_CONVERSION_EITS:
        str=strdup("MAPI_CONVERSION_EITS");
        break;
    case MAPI_CONVERSION_WITH_LOSS_PROHIBITED:
        str=strdup("MAPI_CONVERSION_WITH_LOSS_PROHIBITED");
        break;
    case MAPI_CONVERTED_EITS:
        str=strdup("MAPI_CONVERTED_EITS");
        break;
    case MAPI_DEFERRED_DELIVERY_TIME:
        str=strdup("MAPI_DEFERRED_DELIVERY_TIME");
        break;
    case MAPI_DELIVER_TIME:
        str=strdup("MAPI_DELIVER_TIME");
        break;
    case MAPI_DISCARD_REASON:
        str=strdup("MAPI_DISCARD_REASON");
        break;
    case MAPI_DISCLOSURE_OF_RECIPIENTS:
        str=strdup("MAPI_DISCLOSURE_OF_RECIPIENTS");
        break;
    case MAPI_DL_EXPANSION_HISTORY:
        str=strdup("MAPI_DL_EXPANSION_HISTORY");
        break;
    case MAPI_DL_EXPANSION_PROHIBITED:
        str=strdup("MAPI_DL_EXPANSION_PROHIBITED");
        break;
    case MAPI_EXPIRY_TIME:
        str=strdup("MAPI_EXPIRY_TIME");
        break;
    case MAPI_IMPLICIT_CONVERSION_PROHIBITED:
        str=strdup("MAPI_IMPLICIT_CONVERSION_PROHIBITED");
        break;
    case MAPI_IMPORTANCE:
        str=strdup("MAPI_IMPORTANCE");
        break;
    case MAPI_IPM_ID:
        str=strdup("MAPI_IPM_ID");
        break;
    case MAPI_LATEST_DELIVERY_TIME:
        str=strdup("MAPI_LATEST_DELIVERY_TIME");
        break;
    case MAPI_MESSAGE_CLASS:
        str=strdup("MAPI_MESSAGE_CLASS");
        break;
    case MAPI_MESSAGE_DELIVERY_ID:
        str=strdup("MAPI_MESSAGE_DELIVERY_ID");
        break;
    case MAPI_MESSAGE_SECURITY_LABEL:
        str=strdup("MAPI_MESSAGE_SECURITY_LABEL");
        break;
    case MAPI_OBSOLETED_IPMS:
        str=strdup("MAPI_OBSOLETED_IPMS");
        break;
    case MAPI_ORIGINALLY_INTENDED_RECIPIENT_NAME:
        str=strdup("MAPI_ORIGINALLY_INTENDED_RECIPIENT_NAME");
        break;
    case MAPI_ORIGINAL_EITS:
        str=strdup("MAPI_ORIGINAL_EITS");
        break;
    case MAPI_ORIGINATOR_CERTIFICATE:
        str=strdup("MAPI_ORIGINATOR_CERTIFICATE");
        break;
    case MAPI_ORIGINATOR_DELIVERY_REPORT_REQUESTED:
        str=strdup("MAPI_ORIGINATOR_DELIVERY_REPORT_REQUESTED");
        break;
    case MAPI_ORIGINATOR_RETURN_ADDRESS:
        str=strdup("MAPI_ORIGINATOR_RETURN_ADDRESS");
        break;
    case MAPI_PARENT_KEY:
        str=strdup("MAPI_PARENT_KEY");
        break;
    case MAPI_PRIORITY:
        str=strdup("MAPI_PRIORITY");
        break;
    case MAPI_ORIGIN_CHECK:
        str=strdup("MAPI_ORIGIN_CHECK");
        break;
    case MAPI_PROOF_OF_SUBMISSION_REQUESTED:
        str=strdup("MAPI_PROOF_OF_SUBMISSION_REQUESTED");
        break;
    case MAPI_READ_RECEIPT_REQUESTED:
        str=strdup("MAPI_READ_RECEIPT_REQUESTED");
        break;
    case MAPI_RECEIPT_TIME:
        str=strdup("MAPI_RECEIPT_TIME");
        break;
    case MAPI_RECIPIENT_REASSIGNMENT_PROHIBITED:
        str=strdup("MAPI_RECIPIENT_REASSIGNMENT_PROHIBITED");
        break;
    case MAPI_REDIRECTION_HISTORY:
        str=strdup("MAPI_REDIRECTION_HISTORY");
        break;
    case MAPI_RELATED_IPMS:
        str=strdup("MAPI_RELATED_IPMS");
        break;
    case MAPI_ORIGINAL_SENSITIVITY:
        str=strdup("MAPI_ORIGINAL_SENSITIVITY");
        break;
    case MAPI_LANGUAGES:
        str=strdup("MAPI_LANGUAGES");
        break;
    case MAPI_REPLY_TIME:
        str=strdup("MAPI_REPLY_TIME");
        break;
    case MAPI_REPORT_TAG:
        str=strdup("MAPI_REPORT_TAG");
        break;
    case MAPI_REPORT_TIME:
        str=strdup("MAPI_REPORT_TIME");
        break;
    case MAPI_RETURNED_IPM:
        str=strdup("MAPI_RETURNED_IPM");
        break;
    case MAPI_SECURITY:
        str=strdup("MAPI_SECURITY");
        break;
    case MAPI_INCOMPLETE_COPY:
        str=strdup("MAPI_INCOMPLETE_COPY");
        break;
    case MAPI_SENSITIVITY:
        str=strdup("MAPI_SENSITIVITY");
        break;
    case MAPI_SUBJECT:
        str=strdup("MAPI_SUBJECT");
        break;
    case MAPI_SUBJECT_IPM:
        str=strdup("MAPI_SUBJECT_IPM");
        break;
    case MAPI_CLIENT_SUBMIT_TIME:
        str=strdup("MAPI_CLIENT_SUBMIT_TIME");
        break;
    case MAPI_REPORT_NAME:
        str=strdup("MAPI_REPORT_NAME");
        break;
    case MAPI_SENT_REPRESENTING_SEARCH_KEY:
        str=strdup("MAPI_SENT_REPRESENTING_SEARCH_KEY");
        break;
    case MAPI_X400_CONTENT_TYPE:
        str=strdup("MAPI_X400_CONTENT_TYPE");
        break;
    case MAPI_SUBJECT_PREFIX:
        str=strdup("MAPI_SUBJECT_PREFIX");
        break;
    case MAPI_NON_RECEIPT_REASON:
        str=strdup("MAPI_NON_RECEIPT_REASON");
        break;
    case MAPI_RECEIVED_BY_ENTRYID:
        str=strdup("MAPI_RECEIVED_BY_ENTRYID");
        break;
    case MAPI_RECEIVED_BY_NAME:
        str=strdup("MAPI_RECEIVED_BY_NAME");
        break;
    case MAPI_SENT_REPRESENTING_ENTRYID:
        str=strdup("MAPI_SENT_REPRESENTING_ENTRYID");
        break;
    case MAPI_SENT_REPRESENTING_NAME:
        str=strdup("MAPI_SENT_REPRESENTING_NAME");
        break;
    case MAPI_RCVD_REPRESENTING_ENTRYID:
        str=strdup("MAPI_RCVD_REPRESENTING_ENTRYID");
        break;
    case MAPI_RCVD_REPRESENTING_NAME:
        str=strdup("MAPI_RCVD_REPRESENTING_NAME");
        break;
    case MAPI_REPORT_ENTRYID:
        str=strdup("MAPI_REPORT_ENTRYID");
        break;
    case MAPI_READ_RECEIPT_ENTRYID:
        str=strdup("MAPI_READ_RECEIPT_ENTRYID");
        break;
    case MAPI_MESSAGE_SUBMISSION_ID:
        str=strdup("MAPI_MESSAGE_SUBMISSION_ID");
        break;
    case MAPI_PROVIDER_SUBMIT_TIME:
        str=strdup("MAPI_PROVIDER_SUBMIT_TIME");
        break;
    case MAPI_ORIGINAL_SUBJECT:
        str=strdup("MAPI_ORIGINAL_SUBJECT");
        break;
    case MAPI_DISC_VAL:
        str=strdup("MAPI_DISC_VAL");
        break;
    case MAPI_ORIG_MESSAGE_CLASS:
        str=strdup("MAPI_ORIG_MESSAGE_CLASS");
        break;
    case MAPI_ORIGINAL_AUTHOR_ENTRYID:
        str=strdup("MAPI_ORIGINAL_AUTHOR_ENTRYID");
        break;
    case MAPI_ORIGINAL_AUTHOR_NAME:
        str=strdup("MAPI_ORIGINAL_AUTHOR_NAME");
        break;
    case MAPI_ORIGINAL_SUBMIT_TIME:
        str=strdup("MAPI_ORIGINAL_SUBMIT_TIME");
        break;
    case MAPI_REPLY_RECIPIENT_ENTRIES:
        str=strdup("MAPI_REPLY_RECIPIENT_ENTRIES");
        break;
    case MAPI_REPLY_RECIPIENT_NAMES:
        str=strdup("MAPI_REPLY_RECIPIENT_NAMES");
        break;
    case MAPI_RECEIVED_BY_SEARCH_KEY:
        str=strdup("MAPI_RECEIVED_BY_SEARCH_KEY");
        break;
    case MAPI_RCVD_REPRESENTING_SEARCH_KEY:
        str=strdup("MAPI_RCVD_REPRESENTING_SEARCH_KEY");
        break;
    case MAPI_READ_RECEIPT_SEARCH_KEY:
        str=strdup("MAPI_READ_RECEIPT_SEARCH_KEY");
        break;
    case MAPI_REPORT_SEARCH_KEY:
        str=strdup("MAPI_REPORT_SEARCH_KEY");
        break;
    case MAPI_ORIGINAL_DELIVERY_TIME:
        str=strdup("MAPI_ORIGINAL_DELIVERY_TIME");
        break;
    case MAPI_ORIGINAL_AUTHOR_SEARCH_KEY:
        str=strdup("MAPI_ORIGINAL_AUTHOR_SEARCH_KEY");
        break;
    case MAPI_MESSAGE_TO_ME:
        str=strdup("MAPI_MESSAGE_TO_ME");
        break;
    case MAPI_MESSAGE_CC_ME:
        str=strdup("MAPI_MESSAGE_CC_ME");
        break;
    case MAPI_MESSAGE_RECIP_ME:
        str=strdup("MAPI_MESSAGE_RECIP_ME");
        break;
    case MAPI_ORIGINAL_SENDER_NAME:
        str=strdup("MAPI_ORIGINAL_SENDER_NAME");
        break;
    case MAPI_ORIGINAL_SENDER_ENTRYID:
        str=strdup("MAPI_ORIGINAL_SENDER_ENTRYID");
        break;
    case MAPI_ORIGINAL_SENDER_SEARCH_KEY:
        str=strdup("MAPI_ORIGINAL_SENDER_SEARCH_KEY");
        break;
    case MAPI_ORIGINAL_SENT_REPRESENTING_NAME:
        str=strdup("MAPI_ORIGINAL_SENT_REPRESENTING_NAME");
        break;
    case MAPI_ORIGINAL_SENT_REPRESENTING_ENTRYID:
        str=strdup("MAPI_ORIGINAL_SENT_REPRESENTING_ENTRYID");
        break;
    case MAPI_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY:
        str=strdup("MAPI_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY");
        break;
    case MAPI_START_DATE:
        str=strdup("MAPI_START_DATE");
        break;
    case MAPI_END_DATE:
        str=strdup("MAPI_END_DATE");
        break;
    case MAPI_OWNER_APPT_ID:
        str=strdup("MAPI_OWNER_APPT_ID");
        break;
    case MAPI_RESPONSE_REQUESTED:
        str=strdup("MAPI_RESPONSE_REQUESTED");
        break;
    case MAPI_SENT_REPRESENTING_ADDRTYPE:
        str=strdup("MAPI_SENT_REPRESENTING_ADDRTYPE");
        break;
    case MAPI_SENT_REPRESENTING_EMAIL_ADDRESS:
        str=strdup("MAPI_SENT_REPRESENTING_EMAIL_ADDRESS");
        break;
    case MAPI_ORIGINAL_SENDER_ADDRTYPE:
        str=strdup("MAPI_ORIGINAL_SENDER_ADDRTYPE");
        break;
    case MAPI_ORIGINAL_SENDER_EMAIL_ADDRESS:
        str=strdup("MAPI_ORIGINAL_SENDER_EMAIL_ADDRESS");
        break;
    case MAPI_ORIGINAL_SENT_REPRESENTING_ADDRTYPE:
        str=strdup("MAPI_ORIGINAL_SENT_REPRESENTING_ADDRTYPE");
        break;
    case MAPI_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS:
        str=strdup("MAPI_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS");
        break;
    case MAPI_CONVERSATION_TOPIC:
        str=strdup("MAPI_CONVERSATION_TOPIC");
        break;
    case MAPI_CONVERSATION_INDEX:
        str=strdup("MAPI_CONVERSATION_INDEX");
        break;
    case MAPI_ORIGINAL_DISPLAY_BCC:
        str=strdup("MAPI_ORIGINAL_DISPLAY_BCC");
        break;
    case MAPI_ORIGINAL_DISPLAY_CC:
        str=strdup("MAPI_ORIGINAL_DISPLAY_CC");
        break;
    case MAPI_ORIGINAL_DISPLAY_TO:
        str=strdup("MAPI_ORIGINAL_DISPLAY_TO");
        break;
    case MAPI_RECEIVED_BY_ADDRTYPE:
        str=strdup("MAPI_RECEIVED_BY_ADDRTYPE");
        break;
    case MAPI_RECEIVED_BY_EMAIL_ADDRESS:
        str=strdup("MAPI_RECEIVED_BY_EMAIL_ADDRESS");
        break;
    case MAPI_RCVD_REPRESENTING_ADDRTYPE:
        str=strdup("MAPI_RCVD_REPRESENTING_ADDRTYPE");
        break;
    case MAPI_RCVD_REPRESENTING_EMAIL_ADDRESS:
        str=strdup("MAPI_RCVD_REPRESENTING_EMAIL_ADDRESS");
        break;
    case MAPI_ORIGINAL_AUTHOR_ADDRTYPE:
        str=strdup("MAPI_ORIGINAL_AUTHOR_ADDRTYPE");
        break;
    case MAPI_ORIGINAL_AUTHOR_EMAIL_ADDRESS:
        str=strdup("MAPI_ORIGINAL_AUTHOR_EMAIL_ADDRESS");
        break;
    case MAPI_ORIGINALLY_INTENDED_RECIP_ADDRTYPE:
        str=strdup("MAPI_ORIGINALLY_INTENDED_RECIP_ADDRTYPE");
        break;
    case MAPI_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS:
        str=strdup("MAPI_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS");
        break;
    case MAPI_TRANSPORT_MESSAGE_HEADERS:
        str=strdup("MAPI_TRANSPORT_MESSAGE_HEADERS");
        break;
    case MAPI_DELEGATION:
        str=strdup("MAPI_DELEGATION");
        break;
    case MAPI_TNEF_CORRELATION_KEY:
        str=strdup("MAPI_TNEF_CORRELATION_KEY");
        break;
    case MAPI_BODY:
        str=strdup("MAPI_BODY");
        break;
    case MAPI_REPORT_TEXT:
        str=strdup("MAPI_REPORT_TEXT");
        break;
    case MAPI_ORIGINATOR_AND_DL_EXPANSION_HISTORY:
        str=strdup("MAPI_ORIGINATOR_AND_DL_EXPANSION_HISTORY");
        break;
    case MAPI_REPORTING_DL_NAME:
        str=strdup("MAPI_REPORTING_DL_NAME");
        break;
    case MAPI_REPORTING_MTA_CERTIFICATE:
        str=strdup("MAPI_REPORTING_MTA_CERTIFICATE");
        break;
    case MAPI_RTF_SYNC_BODY_CRC:
        str=strdup("MAPI_RTF_SYNC_BODY_CRC");
        break;
    case MAPI_RTF_SYNC_BODY_COUNT:
        str=strdup("MAPI_RTF_SYNC_BODY_COUNT");
        break;
    case MAPI_RTF_SYNC_BODY_TAG:
        str=strdup("MAPI_RTF_SYNC_BODY_TAG");
        break;
    case MAPI_RTF_COMPRESSED:
        str=strdup("MAPI_RTF_COMPRESSED");
        break;
    case MAPI_RTF_SYNC_PREFIX_COUNT:
        str=strdup("MAPI_RTF_SYNC_PREFIX_COUNT");
        break;
    case MAPI_RTF_SYNC_TRAILING_COUNT:
        str=strdup("MAPI_RTF_SYNC_TRAILING_COUNT");
        break;
    case MAPI_ORIGINALLY_INTENDED_RECIP_ENTRYID:
        str=strdup("MAPI_ORIGINALLY_INTENDED_RECIP_ENTRYID");
        break;
    case MAPI_CONTENT_INTEGRITY_CHECK:
        str=strdup("MAPI_CONTENT_INTEGRITY_CHECK");
        break;
    case MAPI_EXPLICIT_CONVERSION:
        str=strdup("MAPI_EXPLICIT_CONVERSION");
        break;
    case MAPI_IPM_RETURN_REQUESTED:
        str=strdup("MAPI_IPM_RETURN_REQUESTED");
        break;
    case MAPI_MESSAGE_TOKEN:
        str=strdup("MAPI_MESSAGE_TOKEN");
        break;
    case MAPI_NDR_REASON_CODE:
        str=strdup("MAPI_NDR_REASON_CODE");
        break;
    case MAPI_NDR_DIAG_CODE:
        str=strdup("MAPI_NDR_DIAG_CODE");
        break;
    case MAPI_NON_RECEIPT_NOTIFICATION_REQUESTED:
        str=strdup("MAPI_NON_RECEIPT_NOTIFICATION_REQUESTED");
        break;
    case MAPI_DELIVERY_POINT:
        str=strdup("MAPI_DELIVERY_POINT");
        break;
    case MAPI_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED:
        str=strdup("MAPI_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED");
        break;
    case MAPI_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT:
        str=strdup("MAPI_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT");
        break;
    case MAPI_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY:
        str=strdup("MAPI_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY");
        break;
    case MAPI_PHYSICAL_DELIVERY_MODE:
        str=strdup("MAPI_PHYSICAL_DELIVERY_MODE");
        break;
    case MAPI_PHYSICAL_DELIVERY_REPORT_REQUEST:
        str=strdup("MAPI_PHYSICAL_DELIVERY_REPORT_REQUEST");
        break;
    case MAPI_PHYSICAL_FORWARDING_ADDRESS:
        str=strdup("MAPI_PHYSICAL_FORWARDING_ADDRESS");
        break;
    case MAPI_PHYSICAL_FORWARDING_ADDRESS_REQUESTED:
        str=strdup("MAPI_PHYSICAL_FORWARDING_ADDRESS_REQUESTED");
        break;
    case MAPI_PHYSICAL_FORWARDING_PROHIBITED:
        str=strdup("MAPI_PHYSICAL_FORWARDING_PROHIBITED");
        break;
    case MAPI_PHYSICAL_RENDITION_ATTRIBUTES:
        str=strdup("MAPI_PHYSICAL_RENDITION_ATTRIBUTES");
        break;
    case MAPI_PROOF_OF_DELIVERY:
        str=strdup("MAPI_PROOF_OF_DELIVERY");
        break;
    case MAPI_PROOF_OF_DELIVERY_REQUESTED:
        str=strdup("MAPI_PROOF_OF_DELIVERY_REQUESTED");
        break;
    case MAPI_RECIPIENT_CERTIFICATE:
        str=strdup("MAPI_RECIPIENT_CERTIFICATE");
        break;
    case MAPI_RECIPIENT_NUMBER_FOR_ADVICE:
        str=strdup("MAPI_RECIPIENT_NUMBER_FOR_ADVICE");
        break;
    case MAPI_RECIPIENT_TYPE:
        str=strdup("MAPI_RECIPIENT_TYPE");
        break;
    case MAPI_REGISTERED_MAIL_TYPE:
        str=strdup("MAPI_REGISTERED_MAIL_TYPE");
        break;
    case MAPI_REPLY_REQUESTED:
        str=strdup("MAPI_REPLY_REQUESTED");
        break;
    case MAPI_REQUESTED_DELIVERY_METHOD:
        str=strdup("MAPI_REQUESTED_DELIVERY_METHOD");
        break;
    case MAPI_SENDER_ENTRYID:
        str=strdup("MAPI_SENDER_ENTRYID");
        break;
    case MAPI_SENDER_NAME:
        str=strdup("MAPI_SENDER_NAME");
        break;
    case MAPI_SUPPLEMENTARY_INFO:
        str=strdup("MAPI_SUPPLEMENTARY_INFO");
        break;
    case MAPI_TYPE_OF_MTS_USER:
        str=strdup("MAPI_TYPE_OF_MTS_USER");
        break;
    case MAPI_SENDER_SEARCH_KEY:
        str=strdup("MAPI_SENDER_SEARCH_KEY");
        break;
    case MAPI_SENDER_ADDRTYPE:
        str=strdup("MAPI_SENDER_ADDRTYPE");
        break;
    case MAPI_SENDER_EMAIL_ADDRESS:
        str=strdup("MAPI_SENDER_EMAIL_ADDRESS");
        break;
    case MAPI_CURRENT_VERSION:
        str=strdup("MAPI_CURRENT_VERSION");
        break;
    case MAPI_DELETE_AFTER_SUBMIT:
        str=strdup("MAPI_DELETE_AFTER_SUBMIT");
        break;
    case MAPI_DISPLAY_BCC:
        str=strdup("MAPI_DISPLAY_BCC");
        break;
    case MAPI_DISPLAY_CC:
        str=strdup("MAPI_DISPLAY_CC");
        break;
    case MAPI_DISPLAY_TO:
        str=strdup("MAPI_DISPLAY_TO");
        break;
    case MAPI_PARENT_DISPLAY:
        str=strdup("MAPI_PARENT_DISPLAY");
        break;
    case MAPI_MESSAGE_DELIVERY_TIME:
        str=strdup("MAPI_MESSAGE_DELIVERY_TIME");
        break;
    case MAPI_MESSAGE_FLAGS:
        str=strdup("MAPI_MESSAGE_FLAGS");
        break;
    case MAPI_MESSAGE_SIZE:
        str=strdup("MAPI_MESSAGE_SIZE");
        break;
    case MAPI_PARENT_ENTRYID:
        str=strdup("MAPI_PARENT_ENTRYID");
        break;
    case MAPI_SENTMAIL_ENTRYID:
        str=strdup("MAPI_SENTMAIL_ENTRYID");
        break;
    case MAPI_CORRELATE:
        str=strdup("MAPI_CORRELATE");
        break;
    case MAPI_CORRELATE_MTSID:
        str=strdup("MAPI_CORRELATE_MTSID");
        break;
    case MAPI_DISCRETE_VALUES:
        str=strdup("MAPI_DISCRETE_VALUES");
        break;
    case MAPI_RESPONSIBILITY:
        str=strdup("MAPI_RESPONSIBILITY");
        break;
    case MAPI_SPOOLER_STATUS:
        str=strdup("MAPI_SPOOLER_STATUS");
        break;
    case MAPI_TRANSPORT_STATUS:
        str=strdup("MAPI_TRANSPORT_STATUS");
        break;
    case MAPI_MESSAGE_RECIPIENTS:
        str=strdup("MAPI_MESSAGE_RECIPIENTS");
        break;
    case MAPI_MESSAGE_ATTACHMENTS:
        str=strdup("MAPI_MESSAGE_ATTACHMENTS");
        break;
    case MAPI_SUBMIT_FLAGS:
        str=strdup("MAPI_SUBMIT_FLAGS");
        break;
    case MAPI_RECIPIENT_STATUS:
        str=strdup("MAPI_RECIPIENT_STATUS");
        break;
    case MAPI_TRANSPORT_KEY:
        str=strdup("MAPI_TRANSPORT_KEY");
        break;
    case MAPI_MSG_STATUS:
        str=strdup("MAPI_MSG_STATUS");
        break;
    case MAPI_MESSAGE_DOWNLOAD_TIME:
        str=strdup("MAPI_MESSAGE_DOWNLOAD_TIME");
        break;
    case MAPI_CREATION_VERSION:
        str=strdup("MAPI_CREATION_VERSION");
        break;
    case MAPI_MODIFY_VERSION:
        str=strdup("MAPI_MODIFY_VERSION");
        break;
    case MAPI_HASATTACH:
        str=strdup("MAPI_HASATTACH");
        break;
    case MAPI_BODY_CRC:
        str=strdup("MAPI_BODY_CRC");
        break;
    case MAPI_NORMALIZED_SUBJECT:
        str=strdup("MAPI_NORMALIZED_SUBJECT");
        break;
    case MAPI_RTF_IN_SYNC:
        str=strdup("MAPI_RTF_IN_SYNC");
        break;
    case MAPI_ATTACH_SIZE:
        str=strdup("MAPI_ATTACH_SIZE");
        break;
    case MAPI_ATTACH_NUM:
        str=strdup("MAPI_ATTACH_NUM");
        break;
    case MAPI_PREPROCESS:
        str=strdup("MAPI_PREPROCESS");
        break;
    case MAPI_ORIGINATING_MTA_CERTIFICATE:
        str=strdup("MAPI_ORIGINATING_MTA_CERTIFICATE");
        break;
    case MAPI_PROOF_OF_SUBMISSION:
        str=strdup("MAPI_PROOF_OF_SUBMISSION");
        break;
    case MAPI_ENTRYID:
        str=strdup("MAPI_ENTRYID");
        break;
    case MAPI_OBJECT_TYPE:
        str=strdup("MAPI_OBJECT_TYPE");
        break;
    case MAPI_ICON:
        str=strdup("MAPI_ICON");
        break;
    case MAPI_MINI_ICON:
        str=strdup("MAPI_MINI_ICON");
        break;
    case MAPI_STORE_ENTRYID:
        str=strdup("MAPI_STORE_ENTRYID");
        break;
    case MAPI_STORE_RECORD_KEY:
        str=strdup("MAPI_STORE_RECORD_KEY");
        break;
    case MAPI_RECORD_KEY:
        str=strdup("MAPI_RECORD_KEY");
        break;
    case MAPI_MAPPING_SIGNATURE:
        str=strdup("MAPI_MAPPING_SIGNATURE");
        break;
    case MAPI_ACCESS_LEVEL:
        str=strdup("MAPI_ACCESS_LEVEL");
        break;
    case MAPI_INSTANCE_KEY:
        str=strdup("MAPI_INSTANCE_KEY");
        break;
    case MAPI_ROW_TYPE:
        str=strdup("MAPI_ROW_TYPE");
        break;
    case MAPI_ACCESS:
        str=strdup("MAPI_ACCESS");
        break;
    case MAPI_ROWID:
        str=strdup("MAPI_ROWID");
        break;
    case MAPI_DISPLAY_NAME:
        str=strdup("MAPI_DISPLAY_NAME");
        break;
    case MAPI_ADDRTYPE:
        str=strdup("MAPI_ADDRTYPE");
        break;
    case MAPI_EMAIL_ADDRESS:
        str=strdup("MAPI_EMAIL_ADDRESS");
        break;
    case MAPI_COMMENT:
        str=strdup("MAPI_COMMENT");
        break;
    case MAPI_DEPTH:
        str=strdup("MAPI_DEPTH");
        break;
    case MAPI_PROVIDER_DISPLAY:
        str=strdup("MAPI_PROVIDER_DISPLAY");
        break;
    case MAPI_CREATION_TIME:
        str=strdup("MAPI_CREATION_TIME");
        break;
    case MAPI_LAST_MODIFICATION_TIME:
        str=strdup("MAPI_LAST_MODIFICATION_TIME");
        break;
    case MAPI_RESOURCE_FLAGS:
        str=strdup("MAPI_RESOURCE_FLAGS");
        break;
    case MAPI_PROVIDER_DLL_NAME:
        str=strdup("MAPI_PROVIDER_DLL_NAME");
        break;
    case MAPI_SEARCH_KEY:
        str=strdup("MAPI_SEARCH_KEY");
        break;
    case MAPI_PROVIDER_UID:
        str=strdup("MAPI_PROVIDER_UID");
        break;
    case MAPI_PROVIDER_ORDINAL:
        str=strdup("MAPI_PROVIDER_ORDINAL");
        break;
    case MAPI_FORM_VERSION:
        str=strdup("MAPI_FORM_VERSION");
        break;
    case MAPI_FORM_CLSID:
        str=strdup("MAPI_FORM_CLSID");
        break;
    case MAPI_FORM_CONTACT_NAME:
        str=strdup("MAPI_FORM_CONTACT_NAME");
        break;
    case MAPI_FORM_CATEGORY:
        str=strdup("MAPI_FORM_CATEGORY");
        break;
    case MAPI_FORM_CATEGORY_SUB:
        str=strdup("MAPI_FORM_CATEGORY_SUB");
        break;
    case MAPI_FORM_HOST_MAP:
        str=strdup("MAPI_FORM_HOST_MAP");
        break;
    case MAPI_FORM_HIDDEN:
        str=strdup("MAPI_FORM_HIDDEN");
        break;
    case MAPI_FORM_DESIGNER_NAME:
        str=strdup("MAPI_FORM_DESIGNER_NAME");
        break;
    case MAPI_FORM_DESIGNER_GUID:
        str=strdup("MAPI_FORM_DESIGNER_GUID");
        break;
    case MAPI_FORM_MESSAGE_BEHAVIOR:
        str=strdup("MAPI_FORM_MESSAGE_BEHAVIOR");
        break;
    case MAPI_DEFAULT_STORE:
        str=strdup("MAPI_DEFAULT_STORE");
        break;
    case MAPI_STORE_SUPPORT_MASK:
        str=strdup("MAPI_STORE_SUPPORT_MASK");
        break;
    case MAPI_STORE_STATE:
        str=strdup("MAPI_STORE_STATE");
        break;
    case MAPI_IPM_SUBTREE_SEARCH_KEY:
        str=strdup("MAPI_IPM_SUBTREE_SEARCH_KEY");
        break;
    case MAPI_IPM_OUTBOX_SEARCH_KEY:
        str=strdup("MAPI_IPM_OUTBOX_SEARCH_KEY");
        break;
    case MAPI_IPM_WASTEBASKET_SEARCH_KEY:
        str=strdup("MAPI_IPM_WASTEBASKET_SEARCH_KEY");
        break;
    case MAPI_IPM_SENTMAIL_SEARCH_KEY:
        str=strdup("MAPI_IPM_SENTMAIL_SEARCH_KEY");
        break;
    case MAPI_MDB_PROVIDER:
        str=strdup("MAPI_MDB_PROVIDER");
        break;
    case MAPI_RECEIVE_FOLDER_SETTINGS:
        str=strdup("MAPI_RECEIVE_FOLDER_SETTINGS");
        break;
    case MAPI_VALID_FOLDER_MASK:
        str=strdup("MAPI_VALID_FOLDER_MASK");
        break;
    case MAPI_IPM_SUBTREE_ENTRYID:
        str=strdup("MAPI_IPM_SUBTREE_ENTRYID");
        break;
    case MAPI_IPM_OUTBOX_ENTRYID:
        str=strdup("MAPI_IPM_OUTBOX_ENTRYID");
        break;
    case MAPI_IPM_WASTEBASKET_ENTRYID:
        str=strdup("MAPI_IPM_WASTEBASKET_ENTRYID");
        break;
    case MAPI_IPM_SENTMAIL_ENTRYID:
        str=strdup("MAPI_IPM_SENTMAIL_ENTRYID");
        break;
    case MAPI_VIEWS_ENTRYID:
        str=strdup("MAPI_VIEWS_ENTRYID");
        break;
    case MAPI_COMMON_VIEWS_ENTRYID:
        str=strdup("MAPI_COMMON_VIEWS_ENTRYID");
        break;
    case MAPI_FINDER_ENTRYID:
        str=strdup("MAPI_FINDER_ENTRYID");
        break;
    case MAPI_CONTAINER_FLAGS:
        str=strdup("MAPI_CONTAINER_FLAGS");
        break;
    case MAPI_FOLDER_TYPE:
        str=strdup("MAPI_FOLDER_TYPE");
        break;
    case MAPI_CONTENT_COUNT:
        str=strdup("MAPI_CONTENT_COUNT");
        break;
    case MAPI_CONTENT_UNREAD:
        str=strdup("MAPI_CONTENT_UNREAD");
        break;
    case MAPI_CREATE_TEMPLATES:
        str=strdup("MAPI_CREATE_TEMPLATES");
        break;
    case MAPI_DETAILS_TABLE:
        str=strdup("MAPI_DETAILS_TABLE");
        break;
    case MAPI_SEARCH:
        str=strdup("MAPI_SEARCH");
        break;
    case MAPI_SELECTABLE:
        str=strdup("MAPI_SELECTABLE");
        break;
    case MAPI_SUBFOLDERS:
        str=strdup("MAPI_SUBFOLDERS");
        break;
    case MAPI_STATUS:
        str=strdup("MAPI_STATUS");
        break;
    case MAPI_ANR:
        str=strdup("MAPI_ANR");
        break;
    case MAPI_CONTENTS_SORT_ORDER:
        str=strdup("MAPI_CONTENTS_SORT_ORDER");
        break;
    case MAPI_CONTAINER_HIERARCHY:
        str=strdup("MAPI_CONTAINER_HIERARCHY");
        break;
    case MAPI_CONTAINER_CONTENTS:
        str=strdup("MAPI_CONTAINER_CONTENTS");
        break;
    case MAPI_FOLDER_ASSOCIATED_CONTENTS:
        str=strdup("MAPI_FOLDER_ASSOCIATED_CONTENTS");
        break;
    case MAPI_DEF_CREATE_DL:
        str=strdup("MAPI_DEF_CREATE_DL");
        break;
    case MAPI_DEF_CREATE_MAILUSER:
        str=strdup("MAPI_DEF_CREATE_MAILUSER");
        break;
    case MAPI_CONTAINER_CLASS:
        str=strdup("MAPI_CONTAINER_CLASS");
        break;
    case MAPI_CONTAINER_MODIFY_VERSION:
        str=strdup("MAPI_CONTAINER_MODIFY_VERSION");
        break;
    case MAPI_AB_PROVIDER_ID:
        str=strdup("MAPI_AB_PROVIDER_ID");
        break;
    case MAPI_DEFAULT_VIEW_ENTRYID:
        str=strdup("MAPI_DEFAULT_VIEW_ENTRYID");
        break;
    case MAPI_ASSOC_CONTENT_COUNT:
        str=strdup("MAPI_ASSOC_CONTENT_COUNT");
        break;
    case MAPI_ATTACHMENT_X400_PARAMETERS:
        str=strdup("MAPI_ATTACHMENT_X400_PARAMETERS");
        break;
    case MAPI_ATTACH_DATA_OBJ:
        str=strdup("MAPI_ATTACH_DATA_OBJ");
        break;
    case MAPI_ATTACH_ENCODING:
        str=strdup("MAPI_ATTACH_ENCODING");
        break;
    case MAPI_ATTACH_EXTENSION:
        str=strdup("MAPI_ATTACH_EXTENSION");
        break;
    case MAPI_ATTACH_FILENAME:
        str=strdup("MAPI_ATTACH_FILENAME");
        break;
    case MAPI_ATTACH_METHOD:
        str=strdup("MAPI_ATTACH_METHOD");
        break;
    case MAPI_ATTACH_LONG_FILENAME:
        str=strdup("MAPI_ATTACH_LONG_FILENAME");
        break;
    case MAPI_ATTACH_PATHNAME:
        str=strdup("MAPI_ATTACH_PATHNAME");
        break;
    case MAPI_ATTACH_RENDERING:
        str=strdup("MAPI_ATTACH_RENDERING");
        break;
    case MAPI_ATTACH_TAG:
        str=strdup("MAPI_ATTACH_TAG");
        break;
    case MAPI_RENDERING_POSITION:
        str=strdup("MAPI_RENDERING_POSITION");
        break;
    case MAPI_ATTACH_TRANSPORT_NAME:
        str=strdup("MAPI_ATTACH_TRANSPORT_NAME");
        break;
    case MAPI_ATTACH_LONG_PATHNAME:
        str=strdup("MAPI_ATTACH_LONG_PATHNAME");
        break;
    case MAPI_ATTACH_MIME_TAG:
        str=strdup("MAPI_ATTACH_MIME_TAG");
        break;
    case MAPI_ATTACH_ADDITIONAL_INFO:
        str=strdup("MAPI_ATTACH_ADDITIONAL_INFO");
        break;
    case MAPI_DISPLAY_TYPE:
        str=strdup("MAPI_DISPLAY_TYPE");
        break;
    case MAPI_TEMPLATEID:
        str=strdup("MAPI_TEMPLATEID");
        break;
    case MAPI_PRIMARY_CAPABILITY:
        str=strdup("MAPI_PRIMARY_CAPABILITY");
        break;
    case MAPI_7BIT_DISPLAY_NAME:
        str=strdup("MAPI_7BIT_DISPLAY_NAME");
        break;
    case MAPI_ACCOUNT:
        str=strdup("MAPI_ACCOUNT");
        break;
    case MAPI_ALTERNATE_RECIPIENT:
        str=strdup("MAPI_ALTERNATE_RECIPIENT");
        break;
    case MAPI_CALLBACK_TELEPHONE_NUMBER:
        str=strdup("MAPI_CALLBACK_TELEPHONE_NUMBER");
        break;
    case MAPI_CONVERSION_PROHIBITED:
        str=strdup("MAPI_CONVERSION_PROHIBITED");
        break;
    case MAPI_DISCLOSE_RECIPIENTS:
        str=strdup("MAPI_DISCLOSE_RECIPIENTS");
        break;
    case MAPI_GENERATION:
        str=strdup("MAPI_GENERATION");
        break;
    case MAPI_GIVEN_NAME:
        str=strdup("MAPI_GIVEN_NAME");
        break;
    case MAPI_GOVERNMENT_ID_NUMBER:
        str=strdup("MAPI_GOVERNMENT_ID_NUMBER");
        break;
    case MAPI_BUSINESS_TELEPHONE_NUMBER:
        str=strdup("MAPI_BUSINESS_TELEPHONE_NUMBER");
        break;
    case MAPI_HOME_TELEPHONE_NUMBER:
        str=strdup("MAPI_HOME_TELEPHONE_NUMBER");
        break;
    case MAPI_INITIALS:
        str=strdup("MAPI_INITIALS");
        break;
    case MAPI_KEYWORD:
        str=strdup("MAPI_KEYWORD");
        break;
    case MAPI_LANGUAGE:
        str=strdup("MAPI_LANGUAGE");
        break;
    case MAPI_LOCATION:
        str=strdup("MAPI_LOCATION");
        break;
    case MAPI_MAIL_PERMISSION:
        str=strdup("MAPI_MAIL_PERMISSION");
        break;
    case MAPI_MHS_COMMON_NAME:
        str=strdup("MAPI_MHS_COMMON_NAME");
        break;
    case MAPI_ORGANIZATIONAL_ID_NUMBER:
        str=strdup("MAPI_ORGANIZATIONAL_ID_NUMBER");
        break;
    case MAPI_SURNAME:
        str=strdup("MAPI_SURNAME");
        break;
    case MAPI_ORIGINAL_ENTRYID:
        str=strdup("MAPI_ORIGINAL_ENTRYID");
        break;
    case MAPI_ORIGINAL_DISPLAY_NAME:
        str=strdup("MAPI_ORIGINAL_DISPLAY_NAME");
        break;
    case MAPI_ORIGINAL_SEARCH_KEY:
        str=strdup("MAPI_ORIGINAL_SEARCH_KEY");
        break;
    case MAPI_POSTAL_ADDRESS:
        str=strdup("MAPI_POSTAL_ADDRESS");
        break;
    case MAPI_COMPANY_NAME:
        str=strdup("MAPI_COMPANY_NAME");
        break;
    case MAPI_TITLE:
        str=strdup("MAPI_TITLE");
        break;
    case MAPI_DEPARTMENT_NAME:
        str=strdup("MAPI_DEPARTMENT_NAME");
        break;
    case MAPI_OFFICE_LOCATION:
        str=strdup("MAPI_OFFICE_LOCATION");
        break;
    case MAPI_PRIMARY_TELEPHONE_NUMBER:
        str=strdup("MAPI_PRIMARY_TELEPHONE_NUMBER");
        break;
    case MAPI_BUSINESS2_TELEPHONE_NUMBER:
        str=strdup("MAPI_BUSINESS2_TELEPHONE_NUMBER");
        break;
    case MAPI_MOBILE_TELEPHONE_NUMBER:
        str=strdup("MAPI_MOBILE_TELEPHONE_NUMBER");
        break;
    case MAPI_RADIO_TELEPHONE_NUMBER:
        str=strdup("MAPI_RADIO_TELEPHONE_NUMBER");
        break;
    case MAPI_CAR_TELEPHONE_NUMBER:
        str=strdup("MAPI_CAR_TELEPHONE_NUMBER");
        break;
    case MAPI_OTHER_TELEPHONE_NUMBER:
        str=strdup("MAPI_OTHER_TELEPHONE_NUMBER");
        break;
    case MAPI_TRANSMITABLE_DISPLAY_NAME:
        str=strdup("MAPI_TRANSMITABLE_DISPLAY_NAME");
        break;
    case MAPI_PAGER_TELEPHONE_NUMBER:
        str=strdup("MAPI_PAGER_TELEPHONE_NUMBER");
        break;
    case MAPI_USER_CERTIFICATE:
        str=strdup("MAPI_USER_CERTIFICATE");
        break;
    case MAPI_PRIMARY_FAX_NUMBER:
        str=strdup("MAPI_PRIMARY_FAX_NUMBER");
        break;
    case MAPI_BUSINESS_FAX_NUMBER:
        str=strdup("MAPI_BUSINESS_FAX_NUMBER");
        break;
    case MAPI_HOME_FAX_NUMBER:
        str=strdup("MAPI_HOME_FAX_NUMBER");
        break;
    case MAPI_COUNTRY:
        str=strdup("MAPI_COUNTRY");
        break;
    case MAPI_LOCALITY:
        str=strdup("MAPI_LOCALITY");
        break;
    case MAPI_STATE_OR_PROVINCE:
        str=strdup("MAPI_STATE_OR_PROVINCE");
        break;
    case MAPI_STREET_ADDRESS:
        str=strdup("MAPI_STREET_ADDRESS");
        break;
    case MAPI_POSTAL_CODE:
        str=strdup("MAPI_POSTAL_CODE");
        break;
    case MAPI_POST_OFFICE_BOX:
        str=strdup("MAPI_POST_OFFICE_BOX");
        break;
    case MAPI_TELEX_NUMBER:
        str=strdup("MAPI_TELEX_NUMBER");
        break;
    case MAPI_ISDN_NUMBER:
        str=strdup("MAPI_ISDN_NUMBER");
        break;
    case MAPI_ASSISTANT_TELEPHONE_NUMBER:
        str=strdup("MAPI_ASSISTANT_TELEPHONE_NUMBER");
        break;
    case MAPI_HOME2_TELEPHONE_NUMBER:
        str=strdup("MAPI_HOME2_TELEPHONE_NUMBER");
        break;
    case MAPI_ASSISTANT:
        str=strdup("MAPI_ASSISTANT");
        break;
    case MAPI_SEND_RICH_INFO:
        str=strdup("MAPI_SEND_RICH_INFO");
        break;
    case MAPI_WEDDING_ANNIVERSARY:
        str=strdup("MAPI_WEDDING_ANNIVERSARY");
        break;
    case MAPI_BIRTHDAY:
        str=strdup("MAPI_BIRTHDAY");
        break;
    case MAPI_HOBBIES:
        str=strdup("MAPI_HOBBIES");
        break;
    case MAPI_MIDDLE_NAME:
        str=strdup("MAPI_MIDDLE_NAME");
        break;
    case MAPI_DISPLAY_NAME_PREFIX:
        str=strdup("MAPI_DISPLAY_NAME_PREFIX");
        break;
    case MAPI_PROFESSION:
        str=strdup("MAPI_PROFESSION");
        break;
    case MAPI_PREFERRED_BY_NAME:
        str=strdup("MAPI_PREFERRED_BY_NAME");
        break;
    case MAPI_SPOUSE_NAME:
        str=strdup("MAPI_SPOUSE_NAME");
        break;
    case MAPI_COMPUTER_NETWORK_NAME:
        str=strdup("MAPI_COMPUTER_NETWORK_NAME");
        break;
    case MAPI_CUSTOMER_ID:
        str=strdup("MAPI_CUSTOMER_ID");
        break;
    case MAPI_TTYTDD_PHONE_NUMBER:
        str=strdup("MAPI_TTYTDD_PHONE_NUMBER");
        break;
    case MAPI_FTP_SITE:
        str=strdup("MAPI_FTP_SITE");
        break;
    case MAPI_GENDER:
        str=strdup("MAPI_GENDER");
        break;
    case MAPI_MANAGER_NAME:
        str=strdup("MAPI_MANAGER_NAME");
        break;
    case MAPI_NICKNAME:
        str=strdup("MAPI_NICKNAME");
        break;
    case MAPI_PERSONAL_HOME_PAGE:
        str=strdup("MAPI_PERSONAL_HOME_PAGE");
        break;
    case MAPI_BUSINESS_HOME_PAGE:
        str=strdup("MAPI_BUSINESS_HOME_PAGE");
        break;
    case MAPI_CONTACT_VERSION:
        str=strdup("MAPI_CONTACT_VERSION");
        break;
    case MAPI_CONTACT_ENTRYIDS:
        str=strdup("MAPI_CONTACT_ENTRYIDS");
        break;
    case MAPI_CONTACT_ADDRTYPES:
        str=strdup("MAPI_CONTACT_ADDRTYPES");
        break;
    case MAPI_CONTACT_DEFAULT_ADDRESS_INDEX:
        str=strdup("MAPI_CONTACT_DEFAULT_ADDRESS_INDEX");
        break;
    case MAPI_CONTACT_EMAIL_ADDRESSES:
        str=strdup("MAPI_CONTACT_EMAIL_ADDRESSES");
        break;
    case MAPI_COMPANY_MAIN_PHONE_NUMBER:
        str=strdup("MAPI_COMPANY_MAIN_PHONE_NUMBER");
        break;
    case MAPI_CHILDRENS_NAMES:
        str=strdup("MAPI_CHILDRENS_NAMES");
        break;
    case MAPI_HOME_ADDRESS_CITY:
        str=strdup("MAPI_HOME_ADDRESS_CITY");
        break;
    case MAPI_HOME_ADDRESS_COUNTRY:
        str=strdup("MAPI_HOME_ADDRESS_COUNTRY");
        break;
    case MAPI_HOME_ADDRESS_POSTAL_CODE:
        str=strdup("MAPI_HOME_ADDRESS_POSTAL_CODE");
        break;
    case MAPI_HOME_ADDRESS_STATE_OR_PROVINCE:
        str=strdup("MAPI_HOME_ADDRESS_STATE_OR_PROVINCE");
        break;
    case MAPI_HOME_ADDRESS_STREET:
        str=strdup("MAPI_HOME_ADDRESS_STREET");
        break;
    case MAPI_HOME_ADDRESS_POST_OFFICE_BOX:
        str=strdup("MAPI_HOME_ADDRESS_POST_OFFICE_BOX");
        break;
    case MAPI_OTHER_ADDRESS_CITY:
        str=strdup("MAPI_OTHER_ADDRESS_CITY");
        break;
    case MAPI_OTHER_ADDRESS_COUNTRY:
        str=strdup("MAPI_OTHER_ADDRESS_COUNTRY");
        break;
    case MAPI_OTHER_ADDRESS_POSTAL_CODE:
        str=strdup("MAPI_OTHER_ADDRESS_POSTAL_CODE");
        break;
    case MAPI_OTHER_ADDRESS_STATE_OR_PROVINCE:
        str=strdup("MAPI_OTHER_ADDRESS_STATE_OR_PROVINCE");
        break;
    case MAPI_OTHER_ADDRESS_STREET:
        str=strdup("MAPI_OTHER_ADDRESS_STREET");
        break;
    case MAPI_OTHER_ADDRESS_POST_OFFICE_BOX:
        str=strdup("MAPI_OTHER_ADDRESS_POST_OFFICE_BOX");
        break;
    case MAPI_STORE_PROVIDERS:
        str=strdup("MAPI_STORE_PROVIDERS");
        break;
    case MAPI_AB_PROVIDERS:
        str=strdup("MAPI_AB_PROVIDERS");
        break;
    case MAPI_TRANSPORT_PROVIDERS:
        str=strdup("MAPI_TRANSPORT_PROVIDERS");
        break;
    case MAPI_DEFAULT_PROFILE:
        str=strdup("MAPI_DEFAULT_PROFILE");
        break;
    case MAPI_AB_SEARCH_PATH:
        str=strdup("MAPI_AB_SEARCH_PATH");
        break;
    case MAPI_AB_DEFAULT_DIR:
        str=strdup("MAPI_AB_DEFAULT_DIR");
        break;
    case MAPI_AB_DEFAULT_PAB:
        str=strdup("MAPI_AB_DEFAULT_PAB");
        break;
    case MAPI_FILTERING_HOOKS:
        str=strdup("MAPI_FILTERING_HOOKS");
        break;
    case MAPI_SERVICE_NAME:
        str=strdup("MAPI_SERVICE_NAME");
        break;
    case MAPI_SERVICE_DLL_NAME:
        str=strdup("MAPI_SERVICE_DLL_NAME");
        break;
    case MAPI_SERVICE_ENTRY_NAME:
        str=strdup("MAPI_SERVICE_ENTRY_NAME");
        break;
    case MAPI_SERVICE_UID:
        str=strdup("MAPI_SERVICE_UID");
        break;
    case MAPI_SERVICE_EXTRA_UIDS:
        str=strdup("MAPI_SERVICE_EXTRA_UIDS");
        break;
    case MAPI_SERVICES:
        str=strdup("MAPI_SERVICES");
        break;
    case MAPI_SERVICE_SUPPORT_FILES:
        str=strdup("MAPI_SERVICE_SUPPORT_FILES");
        break;
    case MAPI_SERVICE_DELETE_FILES:
        str=strdup("MAPI_SERVICE_DELETE_FILES");
        break;
    case MAPI_AB_SEARCH_PATH_UPDATE:
        str=strdup("MAPI_AB_SEARCH_PATH_UPDATE");
        break;
    case MAPI_PROFILE_NAME:
        str=strdup("MAPI_PROFILE_NAME");
        break;
    case MAPI_IDENTITY_DISPLAY:
        str=strdup("MAPI_IDENTITY_DISPLAY");
        break;
    case MAPI_IDENTITY_ENTRYID:
        str=strdup("MAPI_IDENTITY_ENTRYID");
        break;
    case MAPI_RESOURCE_METHODS:
        str=strdup("MAPI_RESOURCE_METHODS");
        break;
    case MAPI_RESOURCE_TYPE:
        str=strdup("MAPI_RESOURCE_TYPE");
        break;
    case MAPI_STATUS_CODE:
        str=strdup("MAPI_STATUS_CODE");
        break;
    case MAPI_IDENTITY_SEARCH_KEY:
        str=strdup("MAPI_IDENTITY_SEARCH_KEY");
        break;
    case MAPI_OWN_STORE_ENTRYID:
        str=strdup("MAPI_OWN_STORE_ENTRYID");
        break;
    case MAPI_RESOURCE_PATH:
        str=strdup("MAPI_RESOURCE_PATH");
        break;
    case MAPI_STATUS_STRING:
        str=strdup("MAPI_STATUS_STRING");
        break;
    case MAPI_X400_DEFERRED_DELIVERY_CANCEL:
        str=strdup("MAPI_X400_DEFERRED_DELIVERY_CANCEL");
        break;
    case MAPI_HEADER_FOLDER_ENTRYID:
        str=strdup("MAPI_HEADER_FOLDER_ENTRYID");
        break;
    case MAPI_REMOTE_PROGRESS:
        str=strdup("MAPI_REMOTE_PROGRESS");
        break;
    case MAPI_REMOTE_PROGRESS_TEXT:
        str=strdup("MAPI_REMOTE_PROGRESS_TEXT");
        break;
    case MAPI_REMOTE_VALIDATE_OK:
        str=strdup("MAPI_REMOTE_VALIDATE_OK");
        break;
    case MAPI_CONTROL_FLAGS:
        str=strdup("MAPI_CONTROL_FLAGS");
        break;
    case MAPI_CONTROL_STRUCTURE:
        str=strdup("MAPI_CONTROL_STRUCTURE");
        break;
    case MAPI_CONTROL_TYPE:
        str=strdup("MAPI_CONTROL_TYPE");
        break;
    case MAPI_DELTAX:
        str=strdup("MAPI_DELTAX");
        break;
    case MAPI_DELTAY:
        str=strdup("MAPI_DELTAY");
        break;
    case MAPI_XPOS:
        str=strdup("MAPI_XPOS");
        break;
    case MAPI_YPOS:
        str=strdup("MAPI_YPOS");
        break;
    case MAPI_CONTROL_ID:
        str=strdup("MAPI_CONTROL_ID");
        break;
    case MAPI_INITIAL_DETAILS_PANE:
        str=strdup("MAPI_INITIAL_DETAILS_PANE");
        break;
    case MAPI_ID_SECURE_MIN:
        str=strdup("MAPI_ID_SECURE_MIN");
        break;
    case MAPI_ID_SECURE_MAX:
        str=strdup("MAPI_ID_SECURE_MAX");
        break;
    default:
        {
             char buf[10];
#if (SIZEOF_INT == 4)
            sprintf(buf,"%04x",d);
#else
            sprintf(buf,"%04hx", d);
#endif
            str=strdup(buf);
        }
        break;
    }
    return str;
}
