/* This file generated by mknames.awk do not edit! */
#define szMAPI_NULL	0x0001	/* MAPI null property */
#define szMAPI_SHORT	0x0002	/* MAPI short (16 bits) */
#define szMAPI_INT	0x0003	/* MAPI integer (32 bits) */
#define szMAPI_FLOAT	0x0004	/* MAPI float (4 bytes) */
#define szMAPI_DOUBLE	0x0005	/* MAPI double */
#define szMAPI_CURRENCY	0x0006	/* MAPI currency (64 bits) */
#define szMAPI_APPTIME	0x0007	/* MAPI application time */
#define szMAPI_ERROR	0x000a	/* MAPI error (32 bits) */
#define szMAPI_BOOLEAN	0x000b	/* MAPI boolean (16 bits) */
#define szMAPI_OBJECT	0x000d	/* MAPI embedded object */
#define szMAPI_INT8BYTE	0x0014	/* MAPI 8 byte signed int */
#define szMAPI_STRING	0x001e	/* MAPI string */
#define szMAPI_UNICODE_STRING	0x001f	/* MAPI unicode-string */
#define szMAPI_SYSTIME	0x0040	/* MAPI time */
#define szMAPI_CLSID	0x0048	/* MAPI OLE GUID */
#define szMAPI_BINARY	0x0102	/* MAPI binary */
extern char* get_mapi_type_str(uint16 d);
