/* This file generated by mknames.awk do not edit! */
#define attOWNER  	0x0000	/* Owner */
#define attSENTFOR	0x0001	/* Sent For */
#define attDELEGATE	0x0002	/* Delegate */
#define attDATESTART	0x0006	/* Date Start */
#define attDATEEND	0x0007	/* Date End */
#define attAIDOWNER	0x0008	/* Owner Appointment ID */
#define attREQUESTRES	0x0009	/* Response Requested. */
#define attFROM   	0x8000	/* From */
#define attSUBJECT	0x8004	/* Subject */
#define attDATESENT	0x8005	/* Date Sent */
#define attDATERECD	0x8006	/* Date Recieved */
#define attMESSAGESTATUS	0x8007	/* Message Status */
#define attMESSAGECLASS	0x8008	/* Message Class */
#define attMESSAGEID	0x8009	/* Message ID */
#define attPARENTID	0x800a	/* Parent ID */
#define attCONVERSATIONID	0x800b	/* Conversation ID */
#define attBODY   	0x800c	/* Body */
#define attPRIORITY	0x800d	/* Priority */
#define attATTACHDATA	0x800f	/* Attachment Data */
#define attATTACHTITLE	0x8010	/* Attachment File Name */
#define attATTACHMETAFILE	0x8011	/* Attachment Meta File */
#define attATTACHCREATEDATE	0x8012	/* Attachment Creation Date */
#define attATTACHMODIFYDATE	0x8013	/* Attachment Modification Date */
#define attDATEMODIFY	0x8020	/* Date Modified */
#define attATTACHTRANSPORTFILENAME	0x9001	/* Attachment Transport Filename */
#define attATTACHRENDDATA	0x9002	/* Attachment Rendering Data */
#define attMAPIPROPS	0x9003	/* MAPI Properties */
#define attRECIPTABLE	0x9004	/* Recipients */
#define attATTACHMENT	0x9005	/* Attachment */
#define attTNEFVERSION	0x9006	/* TNEF Version */
#define attOEMCODEPAGE	0x9007	/* OEM Codepage */
#define attORIGNINALMESSAGECLASS	0x9008	/* Original Message Class */
extern char* get_tnef_name_str(uint16 d);
