/* This file generated by mknames.awk do not edit! */
#define errNoError	0x0000	/* No Error */
#define errNoTNEFFile	0x0001	/* Error : No TNEF File */
#define errUnexpEndFile	0x0002	/* Error : Invalid Read. Unexpected end of input */
#define errInvalidWrite	0x0003	/* Error : Invalid Write. */
#define errMallocMem	0x0004	/* Error : Allocation Memory */
#define errInvalidParameter	0x0005	/* Error : Invalid Parameter */
#define errInvalidAttributType	0x0006	/* Error : Invalid Attribute Type */
#define errInvOpenFile	0x0007	/* Error : Invalid Open file */
#define errInvalidAttributNumer	0x0008	/* Error : Invalid Attribut Numer */
extern char* get_tnef_error_str(uint16 d);
