/* This file generated by mknames.awk do not edit! */
#define szTRIPLES 	0x0000	/* triples */
#define szSTRING  	0x0001	/* string */
#define szTEXT    	0x0002	/* text */
#define szDATE    	0x0003	/* date */
#define szSHORT   	0x0004	/* short */
#define szLONG    	0x0005	/* long */
#define szBYTE    	0x0006	/* byte */
#define szWORD    	0x0007	/* word */
#define szDWORD   	0x0008	/* dword */
#define szMAX     	0x0009	/* max */
extern char* get_tnef_type_str(uint16 d);
