/* This file generated by mknames.awk do not edit! */
#include <stdio.h>
#include <string.h>
#include "sizes.h"
#include "tnef_names.h"

char* get_tnef_name_str(uint16 d)
{
    char* str = NULL;
    switch(d) {
    case attOWNER:
        str=strdup("Owner");
        break;
    case attSENTFOR:
        str=strdup("Sent For");
        break;
    case attDELEGATE:
        str=strdup("Delegate");
        break;
    case attDATESTART:
        str=strdup("Date Start");
        break;
    case attDATEEND:
        str=strdup("Date End");
        break;
    case attAIDOWNER:
        str=strdup("Owner Appointment ID");
        break;
    case attREQUESTRES:
        str=strdup("Response Requested.");
        break;
    case attFROM:
        str=strdup("From");
        break;
    case attSUBJECT:
        str=strdup("Subject");
        break;
    case attDATESENT:
        str=strdup("Date Sent");
        break;
    case attDATERECD:
        str=strdup("Date Recieved");
        break;
    case attMESSAGESTATUS:
        str=strdup("Message Status");
        break;
    case attMESSAGECLASS:
        str=strdup("Message Class");
        break;
    case attMESSAGEID:
        str=strdup("Message ID");
        break;
    case attPARENTID:
        str=strdup("Parent ID");
        break;
    case attCONVERSATIONID:
        str=strdup("Conversation ID");
        break;
    case attBODY:
        str=strdup("Body");
        break;
    case attPRIORITY:
        str=strdup("Priority");
        break;
    case attATTACHDATA:
        str=strdup("Attachment Data");
        break;
    case attATTACHTITLE:
        str=strdup("Attachment File Name");
        break;
    case attATTACHMETAFILE:
        str=strdup("Attachment Meta File");
        break;
    case attATTACHCREATEDATE:
        str=strdup("Attachment Creation Date");
        break;
    case attATTACHMODIFYDATE:
        str=strdup("Attachment Modification Date");
        break;
    case attDATEMODIFY:
        str=strdup("Date Modified");
        break;
    case attATTACHTRANSPORTFILENAME:
        str=strdup("Attachment Transport Filename");
        break;
    case attATTACHRENDDATA:
        str=strdup("Attachment Rendering Data");
        break;
    case attMAPIPROPS:
        str=strdup("MAPI Properties");
        break;
    case attRECIPTABLE:
        str=strdup("Recipients");
        break;
    case attATTACHMENT:
        str=strdup("Attachment");
        break;
    case attTNEFVERSION:
        str=strdup("TNEF Version");
        break;
    case attOEMCODEPAGE:
        str=strdup("OEM Codepage");
        break;
    case attORIGNINALMESSAGECLASS:
        str=strdup("Original Message Class");
        break;
    default:
        {
             char buf[10];
#if (SIZEOF_INT == 4)
            sprintf(buf,"%04x",d);
#else
            sprintf(buf,"%04hx", d);
#endif
            str=strdup(buf);
        }
        break;
    }
    return str;
}
