/* This file generated by mknames.awk do not edit! */
#include <stdio.h>
#include <string.h>
#include "sizes.h"
#include "tnef_errors.h"

char* get_tnef_error_str(uint16 d)
{
    char* str = NULL;
    switch(d) {
    case errNoError:
        str=strdup("No Error");
        break;
    case errNoTNEFFile:
        str=strdup("Error : No TNEF File");
        break;
    case errUnexpEndFile:
        str=strdup("Error : Invalid Read. Unexpected end of input");
        break;
    case errInvalidWrite:
        str=strdup("Error : Invalid Write.");
        break;
    case errMallocMem:
        str=strdup("Error : Allocation Memory");
        break;
    case errInvalidParameter:
        str=strdup("Error : Invalid Parameter");
        break;
    case errInvalidAttributType:
        str=strdup("Error : Invalid Attribute Type");
        break;
    case errInvOpenFile:
        str=strdup("Error : Invalid Open file");
        break;
    case errInvalidAttributNumer:
        str=strdup("Error : Invalid Attribut Numer");
        break;
    default:
        {
             char buf[10];
#if (SIZEOF_INT == 4)
            sprintf(buf,"%04x",d);
#else
            sprintf(buf,"%04hx", d);
#endif
            str=strdup(buf);
        }
        break;
    }
    return str;
}
